services:
  db:
    image: mysql:8.0
    container_name: gowhere_mysql
    environment:
      MYSQL_ROOT_PASSWORD: IOIZ73763jfl
      MYSQL_DATABASE: gowhere
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  redis:
    image: redis:7
    ports:
        - "6378:6379"
  backend:
    build: .
    container_name: gowhere_backend
    image: teadark/gowhere-backend:latest
    command: |
      sh -c "
        ./wait-for-it.sh db:3306 -- \
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: IOIZ73763jfl
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gowhere
    restart: always

volumes:
  mysql_data: